Config = {}

Config.QBMenuName = 'qb-menu'
Config.QBCoreName = 'qb-core'
Config.QBTargetName = 'qb-target'
Config.InventoryName = 'qb-inventory'
Config.QBInputName = 'qb-input'
Config.QBPhoneName = 'qb-phone'
Config.PhoneName = 'qb-phone' -- Can be qb-phone or gksphone (Maybe later can i'll update to use qs-smartphone)
Config.DebugPoly = false
Config.BillingAfterMailTime = 1 -- Time to receive bill after receive mail to take vehicle back (in minutes)
Config.PriceMultiplier = 10 -- The fees price multiplier (It multipliers vehicle price)

Config.RentalSpots = {
    ["Rental1"] = {
        ["SpotName"] = "Rental1",
        ["LabelSpotName"] = "Vehicles - Rental",
        ["PedCoords"] = vector3(-3427.71, 979.14, 7.35),
        ["PedHeading"] = 179.36,
        ["MapBlipSprite"] = 186,
        ["MapBlipColour"] = 83,
        ["TargetIcon"] = "fas fa-magnifying-glass",
        ["PedModel"] = "csb_anita",
        ["PedModelHash"] = 0x0703F106,
        ["VehicleSpawnLocation"] = vector4(-3433.63, 978.0, 3.15, 172.52),
        ["AvailableVehicles"] = {
            [1] = { VehicleSpawnName = "dinghy", VehicleLableName = "Dinghy", RentPrice = 5, MenuIcon = "fas fa-key" },
            [2] = { VehicleSpawnName = "seashark", VehicleLableName = "Seashark", RentPrice = 5, MenuIcon = "fas fa-key" },
            [3] = { VehicleSpawnName = "marquis", VehicleLableName = "Marquis", RentPrice = 40, MenuIcon = "fas fa-key" },
            [4] = { VehicleSpawnName = "avisa", VehicleLableName = "Avisa", RentPrice = 40, MenuIcon = "fas fa-key" },
            [5] = { VehicleSpawnName = "jetmax", VehicleLableName = "Jetmax", RentPrice = 40, MenuIcon = "fas fa-key" },
            [6] = { VehicleSpawnName = "toro", VehicleLableName = "Toro", RentPrice = 40, MenuIcon = "fas fa-key" },
            [7] = { VehicleSpawnName = "speeder", VehicleLableName = "Speeder", RentPrice = 40, MenuIcon = "fas fa-key" },
        },
    },
    ["Rental2"] = {
        ["SpotName"] = "Rental2",
        ["LabelSpotName"] = "Vehicles - Rental",
        ["PedCoords"] = vector3(-753.53, -1512.41, 5.02),
        ["PedHeading"] = 212.36,
        ["MapBlipSprite"] = 186,
        ["MapBlipColour"] = 83,
        ["TargetIcon"] = "fas fa-magnifying-glass",
        ["PedModel"] = "csb_anita",
        ["PedModelHash"] = 0x0703F106,
        ["VehicleSpawnLocation"] = vector4(-798.67, -1502.49, 2.0, 180.19),
        ["AvailableVehicles"] = {
            [1] = { VehicleSpawnName = "dinghy", VehicleLableName = "Dinghy", RentPrice = 5, MenuIcon = "fas fa-key" },
            [2] = { VehicleSpawnName = "seashark", VehicleLableName = "Seashark", RentPrice = 5, MenuIcon = "fas fa-key" },
            [3] = { VehicleSpawnName = "marquis", VehicleLableName = "Marquis", RentPrice = 40, MenuIcon = "fas fa-key" },
            [4] = { VehicleSpawnName = "avisa", VehicleLableName = "Avisa", RentPrice = 40, MenuIcon = "fas fa-key" },
            [5] = { VehicleSpawnName = "jetmax", VehicleLableName = "Jetmax", RentPrice = 40, MenuIcon = "fas fa-key" },
            [6] = { VehicleSpawnName = "toro", VehicleLableName = "Toro", RentPrice = 40, MenuIcon = "fas fa-key" },
            [7] = { VehicleSpawnName = "speeder", VehicleLableName = "Speeder", RentPrice = 40, MenuIcon = "fas fa-key" },
        },
    },
    ["Rental3"] = {
        ["SpotName"] = "Rental3",
        ["LabelSpotName"] = "Vehicles - Rental",
        ["PedCoords"] = vector3(1396.59, 4283.67, 36.19),
        ["PedHeading"] = 129.36,
        ["MapBlipSprite"] = 186,
        ["MapBlipColour"] = 83,
        ["TargetIcon"] = "fas fa-magnifying-glass",
        ["PedModel"] = "csb_anita",
        ["PedModelHash"] = 0x0703F106,
        ["VehicleSpawnLocation"] = vector4(1426.2, 4263.92, 33.71, 210.88),
        ["AvailableVehicles"] = {
            [1] = { VehicleSpawnName = "dinghy", VehicleLableName = "Dinghy", RentPrice = 5, MenuIcon = "fas fa-key" },
            [2] = { VehicleSpawnName = "seashark", VehicleLableName = "Seashark", RentPrice = 5, MenuIcon = "fas fa-key" },
            [3] = { VehicleSpawnName = "marquis", VehicleLableName = "Marquis", RentPrice = 40, MenuIcon = "fas fa-key" },
            [4] = { VehicleSpawnName = "avisa", VehicleLableName = "Avisa", RentPrice = 40, MenuIcon = "fas fa-key" },
            [5] = { VehicleSpawnName = "jetmax", VehicleLableName = "Jetmax", RentPrice = 40, MenuIcon = "fas fa-key" },
            [6] = { VehicleSpawnName = "toro", VehicleLableName = "Toro", RentPrice = 40, MenuIcon = "fas fa-key" },
            [7] = { VehicleSpawnName = "speeder", VehicleLableName = "Speeder", RentPrice = 40, MenuIcon = "fas fa-key" },
        },
    },
    ["Rental4"] = {
        ["SpotName"] = "Rental4",
        ["LabelSpotName"] = "Vehicles - Rental",
        ["PedCoords"] = vector3(-1600.7, 5204.23, 4.31),
        ["PedHeading"] = 209.36,
        ["MapBlipSprite"] = 186,
        ["MapBlipColour"] = 83,
        ["TargetIcon"] = "fas fa-magnifying-glass",
        ["PedModel"] = "csb_anita",
        ["PedModelHash"] = 0x0703F106,
        ["VehicleSpawnLocation"] = vector4(-1646.02, 5218.22, 6.72, 85.4),
        ["AvailableVehicles"] = {
            [1] = { VehicleSpawnName = "dinghy", VehicleLableName = "Dinghy", RentPrice = 5, MenuIcon = "fas fa-key" },
            [2] = { VehicleSpawnName = "seashark", VehicleLableName = "Seashark", RentPrice = 5, MenuIcon = "fas fa-key" },
            [3] = { VehicleSpawnName = "marquis", VehicleLableName = "Marquis", RentPrice = 40, MenuIcon = "fas fa-key" },
            [4] = { VehicleSpawnName = "avisa", VehicleLableName = "Avisa", RentPrice = 40, MenuIcon = "fas fa-key" },
            [5] = { VehicleSpawnName = "jetmax", VehicleLableName = "Jetmax", RentPrice = 40, MenuIcon = "fas fa-key" },
            [6] = { VehicleSpawnName = "toro", VehicleLableName = "Toro", RentPrice = 40, MenuIcon = "fas fa-key" },
            [7] = { VehicleSpawnName = "speeder", VehicleLableName = "Speeder", RentPrice = 40, MenuIcon = "fas fa-key" },
        },
    },
    ["Rental5"] = {
        ["SpotName"] = "Rental5",
        ["LabelSpotName"] = "Vehicles - Rental",
        ["PedCoords"] = vector3(1297.47, -3309.32, 4.91),
        ["PedHeading"] = 76.38,
        ["MapBlipSprite"] = 186,
        ["MapBlipColour"] = 83,
        ["TargetIcon"] = "fas fa-magnifying-glass",
        ["PedModel"] = "csb_anita",
        ["PedModelHash"] = 0x0703F106,
        ["VehicleSpawnLocation"] = vector4(1307.95, -3308.92, 2.55, 275.88),
        ["AvailableVehicles"] = {
            [1] = { VehicleSpawnName = "dinghy", VehicleLableName = "Dinghy", RentPrice = 5, MenuIcon = "fas fa-key" },
            [2] = { VehicleSpawnName = "seashark", VehicleLableName = "Seashark", RentPrice = 5, MenuIcon = "fas fa-key" },
            [3] = { VehicleSpawnName = "marquis", VehicleLableName = "Marquis", RentPrice = 40, MenuIcon = "fas fa-key" },
            [4] = { VehicleSpawnName = "avisa", VehicleLableName = "Avisa", RentPrice = 40, MenuIcon = "fas fa-key" },
            [5] = { VehicleSpawnName = "jetmax", VehicleLableName = "Jetmax", RentPrice = 40, MenuIcon = "fas fa-key" },
            [6] = { VehicleSpawnName = "toro", VehicleLableName = "Toro", RentPrice = 40, MenuIcon = "fas fa-key" },
            [7] = { VehicleSpawnName = "speeder", VehicleLableName = "Speeder", RentPrice = 40, MenuIcon = "fas fa-key" },
        },
    },
    ["Rental6"] = {
        ["SpotName"] = "Rental6",
        ["LabelSpotName"] = "Vehicles - Rental",
        ["PedCoords"] = vector3(5118.0, -5190.75, 2.38),
        ["PedHeading"] = 344.11,
        ["MapBlipSprite"] = 186,
        ["MapBlipColour"] = 83,
        ["TargetIcon"] = "fas fa-magnifying-glass",
        ["PedModel"] = "csb_anita",
        ["PedModelHash"] = 0x0703F106,
        ["VehicleSpawnLocation"] = vector4(5100.84, -5206.23, 1.96, 359.46),
        ["AvailableVehicles"] = {
            [1] = { VehicleSpawnName = "dinghy", VehicleLableName = "Dinghy", RentPrice = 5, MenuIcon = "fas fa-key" },
            [2] = { VehicleSpawnName = "seashark", VehicleLableName = "Seashark", RentPrice = 5, MenuIcon = "fas fa-key" },
            [3] = { VehicleSpawnName = "marquis", VehicleLableName = "Marquis", RentPrice = 40, MenuIcon = "fas fa-key" },
            [4] = { VehicleSpawnName = "avisa", VehicleLableName = "Avisa", RentPrice = 40, MenuIcon = "fas fa-key" },
            [5] = { VehicleSpawnName = "jetmax", VehicleLableName = "Jetmax", RentPrice = 40, MenuIcon = "fas fa-key" },
            [6] = { VehicleSpawnName = "toro", VehicleLableName = "Toro", RentPrice = 40, MenuIcon = "fas fa-key" },
            [7] = { VehicleSpawnName = "speeder", VehicleLableName = "Speeder", RentPrice = 40, MenuIcon = "fas fa-key" },
        },
    },

    ["Rental7"] = {
        ["SpotName"] = "Rental7",
        ["LabelSpotName"] = "Vehicles - Rental",
        ["PedCoords"] = vector3(525.57, -2853.71, 6.05),
        ["PedHeading"] = 344.11,
        ["MapBlipSprite"] = 186,
        ["MapBlipColour"] = 83,
        ["TargetIcon"] = "fas fa-magnifying-glass",
        ["PedModel"] = "csb_anita",
        ["PedModelHash"] = 0x0703F106,
        ["VehicleSpawnLocation"] = vector4(514.66, -2847.61, 3.83, 164.54),
        ["AvailableVehicles"] = {
            [1] = { VehicleSpawnName = "dinghy", VehicleLableName = "Dinghy", RentPrice = 5, MenuIcon = "fas fa-key" },
            [2] = { VehicleSpawnName = "seashark", VehicleLableName = "Seashark", RentPrice = 5, MenuIcon = "fas fa-key" },
            [3] = { VehicleSpawnName = "marquis", VehicleLableName = "Marquis", RentPrice = 40, MenuIcon = "fas fa-key" },
            [4] = { VehicleSpawnName = "avisa", VehicleLableName = "Avisa", RentPrice = 40, MenuIcon = "fas fa-key" },
            [5] = { VehicleSpawnName = "jetmax", VehicleLableName = "Jetmax", RentPrice = 40, MenuIcon = "fas fa-key" },
            [6] = { VehicleSpawnName = "toro", VehicleLableName = "Toro", RentPrice = 40, MenuIcon = "fas fa-key" },
            [7] = { VehicleSpawnName = "speeder", VehicleLableName = "Speeder", RentPrice = 40, MenuIcon = "fas fa-key" },
        },
    },

    ["Rental8"] = {
        ["SpotName"] = "Rental8",
        ["LabelSpotName"] = "Vehicles - Rental",
        ["PedCoords"] = vector3(5144.17, -5140.41, 1.17),
        ["PedHeading"] = 188.98,
        ["MapBlipSprite"] = 186,
        ["MapBlipColour"] = 83,
        ["TargetIcon"] = "fas fa-magnifying-glass",
        ["PedModel"] = "csb_anita",
        ["PedModelHash"] = 0x0703F106,
        ["VehicleSpawnLocation"] = vector4(5143.15, -5145.4, 3.2, 269.73),
        ["AvailableVehicles"] = {
            [1] = { VehicleSpawnName = "caracara", VehicleLableName = "Caracara", RentPrice = 50, MenuIcon = "fas fa-key" },
            [2] = { VehicleSpawnName = "technical3", VehicleLableName = "Technical", RentPrice = 100, MenuIcon = "fas fa-key" },
            [3] = { VehicleSpawnName = "barrage", VehicleLableName = "Barrage", RentPrice = 200, MenuIcon = "fas fa-key" },
        },
    },
    
}

Lang = {
    ["MenuHeader"] = "BOAT RENTALS",
    ["CloseMenu"] = "EXIT",
    ["InputHeader"] = "HOW MANY MINUTES?",
    ["Submit"] = "SUBMIT",
    ["InputText"] = "TIME [MIN]",
    ["AlreadyRenting"] = "YOU ALREADY HAVE A VEHICLE",
    ["NoMoney"] = "NO MONEYS",
    ["CancelCurrentRenting"] = "CANCEL RENTAL",
    ["ConfirmMenuHeader"] = "ARE YOU SURE?",
    ["Yes"] = "YES",
    ["No"] = "NO",
    ["MailSender"] = "RENTALS",
    ["MailSubject"] = "DETAILS",
    ["MailMessage"] = "Rental timer! <br> You have 5 minutes to take the vehicle back to our department!",
    ["MailMessage2"] = "Renal expired! <br> Make additioanl payments! ",
    ["PerMinute"] = " PER MIN",
}